### ISSUE TITLE
Failed to open rtlsdr device

### ISSUE THREAD

**Issue by djmalin** [catduckgnaf/rtl_433_haos_addon#10]
Hello, my problem is that I cannot run your add-on, I have two tuners, one of which reads the data provided by wmbusmeters and the other rtl_433 (old add-on 0.4.0), now I would like to switch to your new add-on, but the following is displayed: mistake:

>s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
rtl_433 version 23.11-41-g06b03b7a branch master at 202402051043 inputs file rtl_tcp RTL-SDR
newmodel option (-M) is deprecated.
New defaults active, use "-Y classic -s 250k" if you need the old defaults
MQTT: Publishing MQTT data to 192.168.1.70 port 1883
MQTT: Publishing events info to MQTT topic "rtl_433/9b13b3f4-rtl433/events".
Detached kernel driver
Found Fitipower FC0012 tuner
[SDR] Using device 0: Realtek, RTL2838UHIDIR, SN: 00000000, "Generic RTL2832U OEM"
SDR: Using device 0: Realtek, RTL2838UHIDIR, SN: 00000000, "Generic RTL2832U OEM"
Exact sample rate is: 250000.000414 Hz
Allocating 15 zero-copy buffers

my configuration in the config file:

> report_meta stats
report_meta time:iso:usec:tz
report_meta protocol
gain 0
device 0 :00000000
convert si
frequency     868M
hop_interval  600
sample_rate   250k
pulse_detect autolevel
verbose 3
output mqtt://192.168.x.xx:1883,user=xxxx,pass=xxxxx,retain=0,events=rtl_433/9b13b3f4-rtl433/events
output kv
output json:/config/rtl_433/logs/output.json
protocol  172 # Bresser Weather Center 6-in-1, 7-in-1 indoor, soil, new 5-in-1, 3-in-1 wind gauge, Froggit WH6000, Ventus C8488A

my system:

> Core 2024.2.1
Supervisor 2024.01.1
Operating System 11.5
Interfejs użytkownika 20240207.1

**Comment by catduckgnaf** [comment]
other than
 `newmodel option (-M) is deprecated.
New defaults active, use "-Y classic -s 250k" if you need the old defaults`
is it not working? it looks like it should be working. I also notice your retain is 0 and your output structure doesn't match the updated output structure (see my conf file)

**Comment by catduckgnaf** [comment]
@djmalin is it working?
