### ISSUE TITLE
Auto Discovery not working

### ISSUE THREAD

**Issue by djmalin** [catduckgnaf/rtl_433_haos_addon#11]
Hello, I managed to run the add-on but it does not detect a new device in mqtt?.  The program detects my station, but does not add it to mqtt

info sys:

> Core 2024.2.2
Supervisor 2024.02.0
Operating System 12.0.rc1

this is my configuration:
Current version: 2024.2.8

> rtl_433_conf_file: /config/rtl_433/rtl_433.conf
discovery: true
discovery_host: mqtt://core-mosquitto
discovery_port: 1883
discovery_user: xxxx
discovery_password: xxxxx
discovery_topic: rtl_433/+/events
discovery_prefix: homeassistant
discovery_interval: 600
other_args: ""
discovery_ids: Bresser

configuration file (rtl_433.conf)

> report_meta stats
report_meta time:iso:usec:tz
report_meta protocol
gain 0
device 1
convert si
frequency     868.30M
hop_interval  600
sample_rate   250k
pulse_detect autolevel
verbose 6
output kv
output json:/config/rtl_433/logs/output.json
protocol 172
protocol 173
output mqtt://192.168.xx.xx:1883,user=xxxx,pass=xxxxx,retain=1,devices=rtl_433/9b13b3f4-rtl433/devices[/type][/model][/subtype][/channel][/id],events=rtl_433/9b13b3f4-rtl433/events,states=rtl_433/9b13b3f4-rtl433/states

log:

> [SDR] trying device 1: Realtek, RTL2838UHIDIR, SN: 00000001
SDR: trying device 1: Realtek, RTL2838UHIDIR, SN: 00000001
Detached kernel driver
Found Rafael Micro R820T/2 tuner
[SDR] Using device 1: Realtek, RTL2838UHIDIR, SN: 00000001, "Generic RTL2832U OEM"
SDR: Using device 1: Realtek, RTL2838UHIDIR, SN: 00000001, "Generic RTL2832U OEM"
Exact sample rate is: 250000.000414 Hz
[SDR] Sample rate set to 250000 S/s.
SDR: Sample rate set to 250000 S/s.
[Input] Bit detection level set to 0.0 (Auto).
Input: Bit detection level set to 0.0 (Auto).
[SDR] Tuner gain set to Auto.
SDR: Tuner gain set to Auto.
[Input] Reading samples in async mode...
Input: Reading samples in async mode...
[SDR] Tuned to 868.300MHz.
SDR: Tuned to 868.300MHz.
Allocating 15 zero-copy buffers
[MQTT] MQTT Connected...
MQTT: MQTT Connected...
[MQTT] MQTT Connection established.
MQTT: MQTT Connection established.
[Baseband] low pass filter for 250000 Hz at cutoff 50000 Hz, 20.0 us
Baseband: low pass filter for 250000 Hz at cutoff 50000 Hz, 20.0 us
time      : 2024-02-18T19:19:44.295129+0100
Protocol  : 172
model     : Bresser-6in1
id        : 20b001be
channel   : 0
Sensor type: 1
Wind Gust : 0.0 m/s
Wind Speed: 0.0 m/s
Direction : 112
Rain      : 160.4 mm
Startup   : 1
Flags     : 1
Integrity : CRC
[pulse_slicer_pcm] Bresser Weather Center 6-in-1, 7-in-1 indoor, soil, new 5-in-1, 3-in-1 wind gauge, Froggit WH6000, Ventus C8488A
codes     : {275}555555555516ea1796105800df0c7fffff88947ff4fdff809f8000000000000000000
pulse_slicer_pcm: Bresser Weather Center 6-in-1, 7-in-1 indoor, soil, new 5-in-1, 3-in-1 wind gauge, Froggit WH6000, Ventus C8488A codes [{275}555555555516ea1796105800df0c7fffff88947ff4fdff809f8000000000000000000]

**Comment by catduckgnaf** [comment]
Under discovery ID, you need to put the numerical version for the model. The number that Aligns with the line you uncommented in the config. 

So far these issues are more of a support issue, not an add-on issue, encourage you to join the discord there for troubleshooting.
