### ISSUE TITLE
no devices in HA

### ISSUE THREAD

**Issue by mworsnop** [catduckgnaf/rtl_433_haos_addon#14]
I have a handful of Acurite thermometers. I changed the configuration file and took the minus sign out. In the Json log, I can see the data. In MQTT, I see the initial connection. But I do not see any data coming over on MQTT. I am guessing I supposed to have done something else, but I have no idea what it is.

**Comment by catduckgnaf** [comment]
Hello,

If you have not used rtl_433 before, this add-on is not for you. You need to set up MQTT manually. The discovery script sucks, and doesn't work, a true integration is needed and doesn't exist.

I currently do not have the time to build that integration by myself. It really is unfortunate nobody wants to contribute and work on with me/get started. 

Until then, bluntly, don't bother trying to get rtl_433 to work.
