### ISSUE TITLE
Rebuild containers ?

### ISSUE THREAD

**Issue by Mart124** [catduckgnaf/rtl_433_haos_addon#7]
HI @catduckgnaf,

Could it be possible to force a rebuild of your containers, to get the latest rtl_433 commits ?

Thank you very much 👍

**Comment by catduckgnaf** [comment]
@Mart124 is there a device you are looking for? Monthly I sync nightly to https://github.com/catduckgnaf/rtl_433

That way we get a nice stable rolling release of rtl_433, without needing to do nightly and breaking changes, or stay on the outdated last.  You should have the latest if you update. Let me know

**Comment by Mart124** [comment]
Many thanks for your reply @catduckgnaf !
I'm looking for protocol 173, which has been updated a few hours ago to support new Bresser devices.
Let me then update my add-on and give a try :)
Thank you !

**Comment by Mart124** [comment]
Strangely enough last update (`2024.2.0`) still runs an older rtl_433 version :
`rtl_433 version -128-NOTFOUND branch master at 202401280850 inputs file rtl_tcp RTL-SDR`

**Comment by catduckgnaf** [comment]
I know this seems silly, but confirm device doesn't work?

**Comment by Mart124** [comment]
I confirm, the 2 newly added devices do not get detected (whereas the already existing one, with same protocol, properly works).

**Comment by catduckgnaf** [comment]
@Mart124 rebuilding another version now, not sure why that did not sync. should be able to check for an update any minute

**Comment by Mart124** [comment]
Now running `2024.2.3`, but logs still show :
`rtl_433 version -128-NOTFOUND branch master at 202401280850 inputs file rtl_tcp RTL-SDR`
Will give next build a try, we never know :)

**Comment by catduckgnaf** [comment]
Let it run... It may still have the correct file, i'll look at later

**Comment by catduckgnaf** [comment]
Im changing to checkout from the primary rtl_433 branch, I had cloned to mine, because there were some errors that had not been fixed, but lets do this. 

versions moving fast today. Also discovery still doesn't work.... but everything else is fine.

**Comment by Mart124** [comment]
Works perfectly now, thank you very much !
Everything is fine yes (I personally don't use discovery), many thanks for the good job 👍

**Comment by catduckgnaf** [comment]
@Mart124 Awesome! Thank you!
If you want to take a look at the discovery script in the other repo (so we can help others do things less manually feel free). 
Going forward it should always just pull the main nightly now, whenever I update the container. (hopefully only monthly when things are stable)

**Comment by Mart124** [comment]
Note that I had to manually set a _Discovery ID_ in add-on configuration (despite discovery was disabled), without add-on did not want to start.
What would then be a proper default value ?

**Comment by catduckgnaf** [comment]
@Mart124 For now, since that really isn't work. I just removed it.
Ideally only should be if discovery is enabled, etc. 

I will test more before pushing, so now I actually have people using it! Hopefully you like how I did things with the conf file and template. I tried to do what I would expect from modern design.

And join our discord if you want!

**Comment by Mart124** [comment]
@catduckgnaf strangely enough your last builds properly use the rtl_433 master branch (as per the build logs), but then Home Assistant launches :
`rtl_433 version 23.11-40-ge676082b branch master at 202402031407`
As if the rtl_433 compiled binary was not properly copied into the container... Strange !

**Comment by catduckgnaf** [comment]
@Mart124 I will try rebuilding, I apologize for pushing this one without testing more.
I added some docker configs. Can you check for updates and try again?

**Comment by Mart124** [comment]
Don't worry, thank you for your reply !
Same issue with the last build, as if there were some caching side-effect somewhere...

**Comment by catduckgnaf** [comment]
@Mart124 is it still working for you?
It might be just naming. I did change my docker a bit

**Comment by Mart124** [comment]
Yes still works 👍
The issue I mention is that the rtl_433 version compiled during the build is not the one executed by Home Assistant when we install your add-on, which is rather strange...

**Comment by catduckgnaf** [comment]
Thanks, that is strange, it could be simply something naming it wrong. I wonder if it just says the build is different....

I'm taking a break for today. I "think" the discovery should work now, or soon.

**Comment by Mart124** [comment]
Hi @catduckgnaf,
Sorry to bother you again with this, but could it be possible to rebuild the containers, so that we inherit from the last rtl_433 changes please (we added new devices) ?
Thank you very much 👍

**Comment by catduckgnaf** [comment]
@Mart124 Hery there, let me know if its better now, sorry I haven't had as much time to dedicate.
