### ISSUE TITLE
Input device start failed, exiting!

### ISSUE THREAD

**Issue by proyleg** [catduckgnaf/rtl_433_haos_addon#9]
Hi,

I have setup the addon on my Home assistant running under VmaWare workstation on Windows. When I assign the RTL2838UHIDIR device to the VM and start the addon, everything works perfectly fine. If I simply restart the addon, I always get this error:

Found Rafael Micro R820T/2 tuner
Exact sample rate is: 250000.000414 Hz
[SDR] Using device 0: Realtek, RTL2838UHIDIR, SN: 00000001, "Generic RTL2832U OEM"
SDR: Using device 0: Realtek, RTL2838UHIDIR, SN: 00000001, "Generic RTL2832U OEM"
Allocating 15 zero-copy buffers
Failed to allocate zero-copy buffer for transfer 1
Falling back to buffers in userspace
Allocating 15 (non-zero-copy) user-space buffers
[Input] Input device start failed, exiting!

The only way to make it work again, is to unplug the device or reboot HA.
I hope you can help

**Comment by catduckgnaf** [comment]
Hello There,

You are likely getting scanning too much. What is your .conf file look like? If you are trying to find all device without auto settings can overload the device

**Comment by proyleg** [comment]
Hi,

I used your sample configuration file and only enabled 3 protocols.
I do not think it has to do with the configuration. It looks like the devices is not properly released when shutting down rtl_433 service. So unplug and replug the device after that I can properly start rtl_433.

**Comment by catduckgnaf** [comment]
> Hi,
> 
> I used your sample configuration file and only enabled 3 protocols.
> I do not think it has to do with the configuration. It looks like the devices is not properly released when shutting down rtl_433 service. So unplug and replug the device after that I can properly start rtl_433.
> 

Interesting, has it worked before with other configurations?

**Comment by proyleg** [comment]
Hi,

I used your sample configuration file and only enabled 3 protocols.
I do not think it has to do with the configuration. It looks like the devices is not properly released when shutting down rtl_433 service. So unplug and replug the device after that I can properly start rtl_433.

Interesting, has it worked before with other configurations?

I am still running it on the Windows platform as a service and don`t have any problems with it. Of course, I want to move it to HA using addon and this is why I want to use your version because it has less limitations. I want to centralize all my HA services on the HA VM.

**Comment by catduckgnaf** [comment]
> Hi,
> 
> I used your sample configuration file and only enabled 3 protocols.
> I do not think it has to do with the configuration. It looks like the devices is not properly released when shutting down rtl_433 service. So unplug and replug the device after that I can properly start rtl_433.
> 
> Interesting, has it worked before with other configurations?
> 
> I am still running it on the Windows platform as a service and don`t have any problems with it. Of course, I want to move it to HA using addon and this is why I want to use your version because it has less limitations. I want to centralize all my HA services on the HA VM.

Hello, I was curious if had worked with a different HAOS docker. It might more to do with VM management. For example would it work on a Windows vm with same hypervisor. Obviously that is alot of extra work, just trying to trouble shoot here.

**Comment by catduckgnaf** [comment]
Hello, take a look here:
https://github.com/merbanan/rtl_433/issues/2621
This might be more of an rtl_433 issue. Do you mind making an issue there? At this time it might be a bit beyond my ability.
I will leave this open, and if you could comment what you find? 

can you try the old add on to see if you have same issue?

**Comment by proyleg** [comment]
> Hello, take a look here: [merbanan/rtl_433#2621](https://github.com/merbanan/rtl_433/issues/2621) This might be more of an rtl_433 issue. Do you mind making an issue there? At this time it might be a bit beyond my ability. I will leave this open, and if you could comment what you find?
> 
> can you try the old add on to see if you have same issue?

I tried on the old add on and I get the same result.
Here is the answer I got from:
        This is a librtl-sdr issue. What might work is to do a usb reset. Try the rtl-sdr-reset tool. 

I haven't found that tool. Would you be able to incorporate it in your addon?
If not, not ideal, my solution would be to monitor your addon and if it is not in running state, reboot the HA VM.

**Comment by catduckgnaf** [comment]
> > Hello, take a look here: [merbanan/rtl_433#2621](https://github.com/merbanan/rtl_433/issues/2621) This might be more of an rtl_433 issue. Do you mind making an issue there? At this time it might be a bit beyond my ability. I will leave this open, and if you could comment what you find?
> > can you try the old add on to see if you have same issue?
> 
> I tried on the old add on and I get the same result. Here is the answer I got from: This is a librtl-sdr issue. What might work is to do a usb reset. Try the rtl-sdr-reset tool.
> 
> I haven't found that tool. Would you be able to incorporate it in your addon? If not, not ideal, my solution would be to monitor your addon and if it is not in running state, reboot the HA VM.

I do believe it is related to your usb. Try a powered USB hub, try a different usb port, etc.
Especially since you got it on the old-addon there is limited I can do. 

If you see detailed logs, I can see about restarting the add-on itself if it runs into that error.

**Comment by catduckgnaf** [comment]
Closing because this is a support issue, not an issue with the add-on. Please join discord for support
